on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: wtnb75/actions/docker@main
      with:
        username: ${{ github.actor }}
        password: ${{ github.token }}
        context: .
        push: "true"
